package com.nta.enums;

public enum MessageType {
    REQUEST_DELIVERY,
    CURRENT_LOCATION,

    NOT_FOUND_SHIPPER,
    DELIVERY_REQUEST,
    UPDATE_SHIPPER_LOCATION,
    FOUND_SHIPPER,
    APPROVED_SHIPPER,

    NUM_SHIPPER_JOINED,
    REQUEST_JOIN_POST,
    POST_WAS_TAKEN,
}
